[package]
name = "arisna_engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
workspace = "../../.."
publish = false

[dependencies]
bevy.workspace = true
bevy_ufbx.workspace = true
ron.workspace = true
serde.workspace = true
toml_edit = { version = "0.25.13", default-features = false, features = ["parse"] }
